apiVersion: v1
kind: Service
metadata:
  labels:
    app: RestaurentMGTsrv
    service: RestaurentMGTsrv
  name: RestaurentMGTsrv
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: RestaurentMGT