apiVersion: apps/v1
kind: Deployment
metadata:
  name: RestaurentMGT
  labels:
    app: RestaurentMGT
spec:
  selector:
    matchLabels:
      app: RestaurentMGT
  replicas:  1
  template:
    metadata:
      labels:
        app: RestaurentMGT
    spec:
      containers:
       - name: RestaurentMGT
         image: evolza/RestaurentMGT:latest
         imagePullPolicy: Always
         ports:
          - containerPort: 8080
            name: rest
      imagePullSecrets:
          - name: notavailable